#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum/version.py`)
ELECTRUM_VERSION=${VERSION_STRING[2]}
ELECTRUM_VERSION=${ELECTRUM_VERSION#\'}
ELECTRUM_VERSION=${ELECTRUM_VERSION%\'}
export ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum/version.py`)
ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
ELECTRUM_APK_VERSION=${ELECTRUM_APK_VERSION#\'}
ELECTRUM_APK_VERSION=${ELECTRUM_APK_VERSION%\'}
export ELECTRUM_APK_VERSION
